[package]
name = "dobot"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

[dependencies]
tokio-serial = "^4.3.3"
tokio = { version = "^0.2.10", features = ["io-util"] }
failure = "^0.1.6"
getset = "^0.0.9"

[dev-dependencies]
toml = "^0.5.6"
serde = { version = "^1.0.104", features = ["derive"] }


[features]
dobot-test = []
